[versions]
guava = "33.0.0-jre"
junit = "5.12.0-M1"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
